### ISSUE TITLE
suggestion for collaboration and anoter reference

### ISSUE THREAD

**Issue by alexlib** [bschumac/ATIV#1]
Hi Benjamin, @bschumac 

Thanks for using openpiv in your project. it's really interesting to learn about new applications based on PIV. Would you like to tell us more about the adaptive part of your analysis? we'd like to learn if it's useful also in other applications. Also, I think that the new versions of openpiv are more robust (seems that you use 0.23.4) and bug-free, maybe it's better to use openpiv as a dependence, so you'll be always aligned with the updates in the core code. 

Another suggestion is to take a look at this article - we used PIV (OpenPIV at that time was URAPIV) to analyse thermal images over a thin heated foild in the boundary layer of an open flume - seems to be close to your application:
https://link.springer.com/article/10.1007%2Fs00348-004-0805-3

**Comment by bschumac** [comment]
Hi Alex,
there is a paper currently in internal review and will be submitted soon. The adaptive part of the algorithm is the HHT which decomposes the signal and then defining the time interval accordingly. 
I am only using a very small part of openPIV and I modified a line here and there. Therefore I unfortunately cannot use it as a dependency. Through your comment I actually realized that the openpiv_fun.py had loads of unnecessary functions which I removed. Thank you for that.

I will have a look at your article, and will let you know as soon as I have published the A-TIV algorithm.
